#spring:
#  application:
#    name: GETWAY
#  cloud:
#   geteway:
#    routes:
#     - id: LoginService
#       uri: http://localhost:8088/dev/login 
#       predicates:
#        - Path= /dev/login/** 
#    discovery:
#      enable: true
#server:
#  port: 9090
#eureka:
#   client:
#      serviceUrl:
#         defaultZone: http://localhost:8761/eureka
##   instance:
##    preferIpAddress: true
#
##     - id: login
##       uri: lb://login
##       predicates:
##        - path=/order/**
#spring:
#  cloud:
#    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#            - GET
#            - POST